---
title: "Homework: Equilibrium Traffic Flow"
subtitle: "4.1, 4.4, 4.8"
author: Hayden Atchley
date: today
date-format: "D MMMM YYYY"
number-sections: false
execute: 
  echo: false
format: pdf
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(flextable)
require(equatags)

hm <- function(vec){
  n <- length(vec)
  hm <- n / sum(1/vec)
  hm
}
```

# 4.1

Given a speed-density relationship of
\begin{align}
v = v_f\left(1-\frac{k}{k_j}\right), \label{vk}
\end{align}
and the relationship $q = k\times v$, we can derive flow-density and speed-flow relationships as follows:
\begin{align}
q &= kv \\
q &= kv_f\left(1-\frac{k}{k_j}\right) \\
q &= kv_f - \frac{k^2v_f}{k_j} \label{qk}
\end{align}  
and
\begin{align}
k = \frac{q}{v},\quad v &= v_f\left(1-\frac{k}{k_j}\right) \\
\implies v &= v_f\left(1-\frac{q/v}{k_j}\right) \\
\implies v^2 &= v_fv - \frac{qv_f}{k_j}. \label{vq}
\end{align}

From \eqref{qk} we can find $q_m$ (the capacity) and $k_m$ (the density at capacity) by determining the maximum of the flow-density relationship (where $\frac{dq}{dk} = 0$):
\begin{align}
q &= kv_f - \frac{k^2v_f}{k_j} \\
\frac{dq}{dk} = 0 &= v_f - 2\frac{k_mv_f}{k_j} \\
0 &= v_f\left(1 - 2\frac{k_m}{k_j}\right) \\
0 &= 1 - 2\frac{k_m}{k_j} \quad \text{if } v_f \neq 0 \\
k_m &= \frac{k_j}{2} \label{km}
\end{align}
\begin{align}
q_m &= k_mv_f \left(1 - \frac{k_m}{k_j}\right) \\
q_m &= \frac{k_jv_f}{2}\left(1 - \frac{k_j/2}{k_j}\right) \\
q_m &= \frac{k_jv_f}{4}. \label{qm}
\end{align}

$v_m$ (the speed at capacity) is then determined from \eqref{qm} and the original relationship \eqref{vk} by:
\begin{align}
v_m &= v_f\left(1 - \frac{k_m}{k_j}\right) \\
v_m &= v_f\left(1 - \frac{k_j/2}{k_j}\right) \\
v_m &= \frac{v_f}{2}.
\end{align}

{{< pagebreak >}}

# 4.4

The Greenberg model is given by
\begin{align}
v = v_m\ln{\frac{k_j}{k}}. \label{greenberg}
\end{align}

The capacity is again determined by setting $\frac{dq}{dk} = 0$, so a flow-density relationship is first determined:
\begin{align}
q = kv = kv_m(\ln k_j - \ln k). \label{gb-qk}
\end{align}

Then:
\begin{align}
\frac{dq}{dk} = 0 &= \frac{d}{dk} kv_m(\ln k_j - \ln k) \\
0 &= k_mv_m\left(-\frac{1}{k_m}\right) + v_m(\ln k_j - \ln k_m) \\
0 &= v_m\left(\ln \frac{k_j}{k_m} - 1\right) \\
1 &= \ln \frac{k_j}{k_m} \quad\text{if } v_m \neq 0 \\
e &= \frac{k_j}{k_m} \\
k_m &= \frac{k_j}{e}. \label{gb-km}
\end{align}

$q_m$ is then given from \eqref{gb-qk} and \eqref{gb-km}:
\begin{align}
q_m = k_mv_m(\ln k_j - \ln k_m) &= k_mv_m\left(\ln \frac{k_j}{k_m}\right) \\
q_m &= \frac{k_jv_m}{e}\left(\ln \frac{k_j}{k_j/e}\right) \\
q_m &= \frac{k_jv_m}{e}
\end{align}

{{< pagebreak >}}

# 4.8

