---
title: "Homework: Conservation"
subtitle: "5.1, 5.3"
author: Hayden Atchley
date: today
date-format: "D MMMM YYYY"
number-sections: false
execute: 
  echo: false
format: pdf
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(flextable)

set_flextable_defaults(
  float = "float"
)
```

# 5.1

```{r}
#| include: false

distance <- 1.5 #miles
interval <- 1 #hours
nlanes <- 2

tunnel <- read_csv("data/tunnel.csv") %>% 
  mutate(time = hour %>% hours() %>% as_datetime())

los <- tribble(
  ~los, ~smin, ~max,
  "A", -Inf, 11,
  "B", 11, 18,
  "C", 18, 26,
  "D", 26, 35,
  "E", 35, 45,
  "F", 45, Inf
) %>% 
  mutate(label = case_when(
    smin <= 0 ~ paste("&le;", max),
    max == Inf ~ paste("&gt;", smin),
    TRUE ~ paste0(smin, "&ndash;", max)
  ))

calc_tunnel <- tunnel %>% 
  mutate(
    sum_vin = cumsum(vin),
    sum_vout = cumsum(vout),
    vtunnel = sum_vin - sum_vout,
    dens = vtunnel / distance,
    dens_lane = dens / nlanes
    ) %>% 
  left_join(los, join_by(between(dens_lane, smin, max, bounds = "(]"))) %>% 
  select(-c(smin, max, label))
```

@tbl-tunnel shows vehicle counts from the Lincoln Tunnel's `r distance`-mile long south tunnel.
The counts are binned by hour over a 24-hour period, and are for both entering and exiting vehicles.

```{r}
#| label: tbl-tunnel
#| tbl-cap: Lincoln Tunnel Vehicle Counts

tunnel %>% 
  flextable(col_keys = c("time", "vin", "vout")) %>% 
  set_header_labels(time = "Time", vin = "Vehicles\nEntering", vout = "Vehicles\nExiting") %>% 
  colformat_datetime(fmt_datetime = "%H:%M") %>% 
  autofit() %>% 
  align(align = "c", part = "a")
```

```{r}
#| label: tbl-calc-tunnel
#| tbl-cap: Density and LOS Calculations for Lincoln Tunnel

calc_tunnel %>% 
  flextable(col_keys = c("time", "sum_vin", "sum_vout", "vtunnel", "dens", "dens_lane", "los")) %>% 
  set_header_labels(
    time = "Time", 
    sum_vin = "Cumulative Vehicles\nEntering",
    sum_vout = "Cumulative Vehicles\nExiting",
    vtunnel = "Vehicles In\nTunnel (En&minus;Ex)",
    dens = "Density\n(veh/mi)",
    dens_lane = "Lane Density\n(veh/mi/lane)",
    los = "Level of\nService"
  ) %>% 
  colformat_datetime(fmt_datetime = "%H:%M") %>% 
  colformat_double(j = ~ dens + dens_lane, digits = 2) %>% 
  autofit() %>% 
  align(align = "c", part = "a")
```

More words.

# 5.3



